# Site settings
title: Geert's Notes
email: geertj@gmail.com
description: Geert's personal blog. Opinions are my own.
baseurl: ""
url: "http://geertj.me"
twitter_username: 1geertj
github_username:  geertj
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
